### ISSUE TITLE
guest log

### ISSUE THREAD

**Issue by seanbreckenridge** [seanbreckenridge/glue#6]
would probably need an approval system/api endpoint

**Comment by jlehrer1** [comment]
Good idea 😊

**Comment by seanbreckenridge** [comment]
[backend/approval system implemented](https://github.com/seanbreckenridge/glue/commit/1a2e760189534297cd3dcf47f1635bf4334e28f9)

need to do the rendering/POST request from frontend now

**Comment by seanbreckenridge** [comment]
done
